#!/bin/bash

echo "packer: updating nginx configuration"
cp -r $HOME/app/mailtube/nginx $HOME/app/nginx

sed -i "s#{NGINX_USER}#$INSTANCE_USER#g" $HOME/app/nginx/nginx.conf
sed -i "s#{NGINX_WORKERS}#$NGINX_WORKERS#g" $HOME/app/nginx/nginx.conf
sed -i "s#{SERVER_NAME}#$SERVER_NAME#g" $HOME/app/nginx/site.conf
sed -i "s#{STATIC_ROOT}#$HOME/app/server/.bin/public#g" $HOME/app/nginx/site.conf

sudo ln -sfn $HOME/app/nginx/nginx.conf /etc/nginx/nginx.conf
sudo ln -sfn $HOME/app/nginx/site.conf /etc/nginx/sites-enabled/$NAME.conf
sudo rm /etc/nginx/sites-enabled/default

sudo service nginx restart || sudo service nginx start || (sudo cat /var/log/nginx/error.log && exit 1)

echo "packer: installing appserver daemon..."
echo "#!/bin/bash" > $HOME/app/start
echo ". $HOME/.nvm/nvm.sh" >> $HOME/app/start
echo "NODE_ENV=$NODE_ENV node $HOME/app/server/cluster.js" >> $HOME/app/start
chmod +x $HOME/app/start
cp $HOME/app/mailtube/init.d/appserver.conf $HOME/app/$NAME.conf
sed -i "s#{NAME}#$NAME#g" $HOME/app/$NAME.conf
sed -i "s#{DESCRIPTION}#Web application daemon service for $NAME#g" $HOME/app/$NAME.conf
sed -i "s#{USER}#$INSTANCE_USER#g" $HOME/app/$NAME.conf
sed -i "s#{COMMAND}#$HOME/app/start#g" $HOME/app/$NAME.conf
sudo mv $HOME/app/$NAME.conf /etc/init.d/$NAME
sudo chmod +x /etc/init.d/$NAME
sudo touch /var/log/$NAME.log
sudo chown $INSTANCE_USER /var/log/$NAME.log
sudo update-rc.d $NAME defaults

echo "packer: sourcing nvm"
. $HOME/.nvm/nvm.sh

echo "packer: moving uploaded server code"
mv /tmp/appserver $HOME/app/server

echo "packer: installing server dependencies"
mv $HOME/app/server/deploy/env/.env.$NODE_ENV.json $HOME/app/server/.env.json
mv $HOME/app/precache/node_modules $HOME/app/server/node_modules
npm install --prefix $HOME/app/server --production

echo "packer: booting appserver daemon..."
sudo service $NAME start

echo "packer: setting up article scheduler cron job"
crontab -l | { cat; echo "*/6 * * * * curl http://localhost:3000/api/scheduler"; } | crontab -
